<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>

<div class="owl-carousel owl-theme slider-base" data-mage-init='{"slider": { "loop": <?php echo $block->getLoop() ? "true" : "false" ?> }}'>
    <div class="item slider-base-item"><h4><img src="https://www.zolotoyvek.ua/media/adminforms/homebanners/cache/1/cache/900x508/5e06319eda06f020e43594a9c230972d/u/k/ukrasheniya-s-izumrudami.jpg"></h4></div>
    <div class="item slider-base-item"><h4><img src="https://www.zolotoyvek.ua/media/adminforms/homebanners/cache/1/cache/900x508/5e06319eda06f020e43594a9c230972d/d/r/dragocennye-kamni-ametist.jpg"></h4></div>
    <div class="item slider-base-item"><h4><img src="https://www.zolotoyvek.ua/media/adminforms/homebanners/cache/1/cache/900x508/5e06319eda06f020e43594a9c230972d/u/k/ukrasheniya-s-raukhtopazom.jpg"></h4></div>
    <div class="item slider-base-item"><h4><img src="https://www.zolotoyvek.ua/media/adminforms/homebanners/cache/1/cache/900x508/5e06319eda06f020e43594a9c230972d/u/k/ukrasheniya-s-rubinamy_1.jpg"></h4></div>
</div>