<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="">
    <div class="container navbar">
        <div class="navbar_item navbar_item__bg-darkness" data-action="show-mega-menu_holder">
            <div class="navbar_item__uppercase">
                <a class="navbar_item-link" href="#">
                    <span class="icon icon__bg-burger"></span>
                    <span>Каталог товаров</span>
                </a>
            </div>
        </div>
        <div class="navbar_item navbar_item__large">
            <div class="navbar_item-search-holder">
                <input class="navbar_item-search-input" type="text" placeholder="Поиск товаров">
            </div>
        </div>
        <div class="navbar_item navbar_item__small">
            <a class="navbar_item-link" href="#">
                <span class="icon icon__bg-filters"></span>
                <span>Подбор товаров</span>
            </a>
        </div>
        <div class="navbar_item navbar_item__bg-darkness navbar_item__small">
            <a class="navbar_item-link" href="#">
                <span class="icon icon__bg-cart"></span>
                <span>Корзина пуста</span>
            </a>
        </div>
    </div>
    <div class="mobile-nav" data-mage-init='{"mobileNav":{}}'>
        <div class="container">
            <div class="navbar_item-icon-holder mobile-nav_icon">
                <a class="navbar_item-link" data-action="show-mobile-dropdown" href="#">
                    <span class="icon icon__bg-burger"></span>
                </a>
            </div>
            <div class="navbar_item-icon-holder mobile-nav_icon">
                <a href="#" class="navbar_item-icon-link">
                    <span class="icon icon__logo"></span>
                </a>
            </div>
            <div class="navbar_item-icon-holder mobile-nav_icon">
                <a href="#" class="navbar_item-icon-link">
                    <span class="icon icon__bg-cart"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="mobile-nav_dropdown mobile-nav_dropdown__hide">
        <div class="mobile-nav_close" data-action="hide-mobile-dropdown"></div>
        <div class="mobile-nav_dropdown-header">Каталог</div>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Кольца</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Серьги</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Подвески</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Цепочки</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Бриллианты</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Украшения с камнями</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Серебро</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__premium">DIAMONDS - премиум-бренд</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__bold">Каталог</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link">Коллекции</span>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Комплекты</a>
            </li>
        </ul>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Доставка и оплата</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Наши магазины</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Акции</a>
            </li>
        </ul>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Отследить заказ</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Бесплатная доставка</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Обмен 14 дней</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Бесплатная бронь в магазине</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Как оплатить</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-more">Больше</span>
            </li>
        </ul>
    </div>
    <div class="container mega-menu" data-mage-init='{"megaMenu": {"home": <?php echo $block->getShowVertical() ? '1' : '0' ?>}}' data-action="show-mega-menu_holder">
        <div class="mega-menu_holder mega-menu_holder__show-horisontal<?php echo !$block->getShowVertical() ? ' mega-menu_holder-page' : '' ?>">
            <ul class="mega-menu-grid">
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" data-action="show-dropbox" href="#">Кольца</a>
                    <div class="mega-menu_dropbox">
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Помолвочные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Фаланговые</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без вставки</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Серьги</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без вставки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-пуссеты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-конго</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221734_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С замком-петелькой</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Подвески</a>
                    <div class="mega-menu_dropbox">
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без ставки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Крестики</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Иконки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Буквы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Знаки зодиака</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Бусины-шарм</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Цепочки</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Золотые</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серебрянные</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Колье</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Ювелирные шнурки</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Бриллианты</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Помолвочные кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Из белого золота</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серьги</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Колье</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Подвески</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Крестики</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Броши</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Ребенку</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Украшения с камнями</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Бриллиант</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Сапфир</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Изумруд</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Рубин</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Топаз</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Раухтопаз</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Жемчуг</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Аметист</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Цитрин</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Гранат</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Хризолит</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Серебро</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серьги</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Подвески</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Цепочки</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Крестики</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Иконки</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Пирсинг</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Этнический орнамент</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Старославянские обереги</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Бусины шарм</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Свадьба</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Помолвочные кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Свадебные подарки</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Юбилей свадьби</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level mega-menu-link__premium">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">DIAMONDS - премиум-бренд</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серьги</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Подвески</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Колье</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Каталог</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Кольца</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серьги</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Подвески</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Сертификаты</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Печатки</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Часы</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Броши</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Зажимы</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Запонки</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Пирсинг</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Коллекции</a>
                    <ul class="mega-menu_list">
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Коллекция "Корона"</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Белое золото</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Украшения с топазами</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Серебро с фианитами</span>
                            </a>
                        </li>
                        <li class="mega-menu_dropbox-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Украшения с сапфирами</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Комплекты</a>
                </li>
            </ul>
        </div>
    </div>
</div>



