<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="container mega-menu" data-mage-init='{"megaMenu": {"home": <?php echo $block->getShowVertical() ? '1' : '0' ?>}}' data-action="show-mega-menu_holder">
    <div class="mega-menu_holder<?php echo !$block->getShowVertical() ? ' mega-menu_holder-page' : '' ?>" data-action="show-mega-menu_horisontal">
        <ul class="mega-menu-grid">
            <?php for ($i = 0; $i < 13; $i++): ?>
                <?php if ($i % 2 == 0): ?>
                    <li class="mega-menu_item mega-menu_item__top-level <?php echo ($i % 4 == 0) ? 'mega-menu-link__premium' : '' ?>">
                        <a class="mega-menu-link mega-menu-link__top-level" data-action="show-dropbox" href="#">Кольца</a>
                        <div class="mega-menu_dropbox">
                            <div class="mega-menu_banner">
                                <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                            </div>
                            <ul class="mega-menu_list">

                                <?php for ($j = 0; $j < 10; $j++): ?>
                                <li class="mega-menu_dropbox-item">
                                    <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                        <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                        <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                    </a>
                                </li>
                                <?php endfor ?>
                                <li class="mega-menu_dropbox-item">
                                    <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                        <span class="mega-menu-link_thumbnail-title">Смотреть все</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                <?php else: ?>
                    <li class="mega-menu_item mega-menu_item__top-level">
                        <a class="mega-menu-link mega-menu-link__top-level" href="#">Украшения с камнями</a>
                        <div class="mega-menu_dropbox">
                            <div class="mega-menu_banner">
                                <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                            </div>
                            <ul class="mega-menu_list">
                                <?php for ($j = 0; $j < 5; $j++): ?>
                                    <li class="mega-menu_dropbox-item">
                                        <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                            <img class="mega-menu-link_thumbnail"
                                                 src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                                 alt="">
                                            <span class="mega-menu-link_thumbnail-title">Сапфир</span>
                                        </a>
                                    </li>
                                    <li class="mega-menu_dropbox-item">
                                        <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                            <img class="mega-menu-link_thumbnail"
                                                 src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                                 alt="">
                                            <span class="mega-menu-link_thumbnail-title">Изумруд</span>
                                        </a>
                                    </li>
                                <?php endfor ?>
                            </ul>
                        </div>
                    </li>
                <?php endif ?>
            <?php endfor ?>
        </ul>
    </div>
</div>
