<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="">
    <div class="container navbar">
        <div class="navbar_item navbar_item__hover navbar_item__bg-darkness" data-action="show-mega-menu_holder">
            <div class="navbar_item__uppercase">
                <a class="navbar_item-link" href="#">
                    <span class="icon icon__bg-burger"></span>
                    <span class="navbar_item__uppercase-label">Каталог товаров</span>
                </a>
            </div>
        </div>
        <div class="navbar_item navbar_item__large">
            <div class="navbar_item-search-holder">
                <input class="navbar_item-search-input" type="search" placeholder="Поиск товаров">
            </div>
        </div>
        <div class="navbar_item navbar_item__hover navbar_item__small">
            <a class="navbar_item-link" href="#">
                <span class="icon icon__bg-filters"></span>
                <span>Подбор товаров</span>
            </a>
        </div>
        <div class="navbar_item navbar_item__hover navbar_item__bg-darkness navbar_item__small">
            <a class="navbar_item-link" href="#">
                <span class="icon icon__bg-cart"></span>
                <span>Корзина пуста</span>
            </a>
        </div>
    </div>
    <div class="mobile-nav" data-mage-init='{"mobileNav":{}}'>
        <div class="container">
            <div class="navbar_item-icon-holder mobile-nav_icon" data-action="show-mobile-dropdown">
                <a href="#" class="navbar_item-burger">
                    <span class="icon icon__bg-burger"></span>
                </a>
            </div>
            <div class="navbar_item-icon-holder mobile-nav_icon">
                <a href="#" class="navbar_item-icon-link">
                    <span class="icon icon__logo"></span>
                </a>
            </div>
            <div class="navbar_item-icon-holder mobile-nav_icon">
                <a href="#" class="navbar_item-icon-link">
                    <span class="icon icon__bg-cart"></span>
                </a>
            </div>
        </div>
    </div>
    <div class="mobile-nav_dropdown mobile-nav_dropdown__hide">
        <div class="mobile-nav_close" data-action="hide-mobile-dropdown"></div>
        <div class="mega-menu_dropdown-box">
            <div class="mobile-nav_dropdown-header" >Каталог</div>
            <ul class="mobile-nav_dropdown-list">
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Кольца</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Серьги</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Подвески</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Цепочки</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Бриллианты</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Украшения с камнями</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Серебро</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">DIAMONDS - премиум-бренд</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link mobile-nav_dropdown-link__bold" data-action="show-mobile-dropdown_second-level">Каталог</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Каталог</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14212922.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Кольца</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Серьги</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14231344.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Подвески</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x1427101-01-0-5070.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142icon_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Сертификаты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14219023.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Печатки</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142_-302_1.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Часы</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x1424099_1.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Броши</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mobile-nav_dropdown-link">
                                    <span class="mobile-nav_dropdown-more">Все товары</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Коллекции</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Комплекты</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
            <ul class="mobile-nav_dropdown-list">
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-map-marker-alt"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Доставка и оплата</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link">Наши магазины</a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link">Акции</a>
                </li>
            </ul>
            <ul class="mobile-nav_dropdown-list">
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-arrows-alt"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Отследить заказ</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-shipping-fast"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Бесплатная доставка</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-retweet"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Обмен 14 дней</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-cart-plus"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Бесплатная бронь в магазине</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-credit-card"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Как оплатить</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <span class="mobile-nav_dropdown-link mobile-nav_dropdown-more" data-action="show-mobile-dropdown_second-level">Больше</span>
                    <div class="mobile-nav_dropdown__second-level">
                        <ul class="mobile-nav_dropdown-list">
                            <li class="mobile-nav_dropdown-item">
                                <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Больше</span>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">О нас</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Производство</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Гарантия качества</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Обмен и возврат</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Рассрочка и кредит</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Контакты</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Дисконтная программа</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Ювелирные мастерские</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Новости</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Вакансии</span>
                                </a>
                            </li>
                            <li class="mobile-nav_dropdown-item">
                                <a href="#" class="mega-menu-link">
                                    <span class="mobile-nav_dropdown-link__without-icon">Вопрос-Ответ</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-search"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Поиск товаров</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="far fa-calendar-check"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Подбор товаров</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-phone"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">099 80 90 833</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="far fa-user"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Войти</span>
                    </a>
                </li>
                <li class="mobile-nav_dropdown-item">
                    <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                        <i class="fas fa-hand-holding-heart"></i>
                        <span class="mobile-nav_dropdown-link__with-icon-label">Мой золотой век</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container mega-menu" data-mage-init='{"megaMenu": {"home": <?php echo $block->getShowVertical() ? '1' : '0' ?>}}' data-action="show-mega-menu_holder">
        <div class="mega-menu_holder mega-menu_holder__show-horisontal<?php echo !$block->getShowVertical() ? ' mega-menu_holder-page' : '' ?>">
            <ul class="mega-menu-grid">
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" data-action="show-dropbox" href="#">Кольца</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Помолвочные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Фаланговые</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без вставки</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Серьги</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без вставки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-пуссеты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-конго</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги-подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221734_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С замком-петелькой</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Подвески</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С бриллиантами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С полудрагоценными камнями</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">С жемчугом</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221612_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Без ставки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14202882_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Эксклюзивы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253705-0.9_-__1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Крестики</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Иконки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Буквы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14220860-2-1200_1.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Знаки зодиака</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255_2.jpg" alt="">
                                    <span class="mega-menu-link_thumbnail-title">Бусины-шарм</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Цепочки</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Золотые</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серебрянные</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Колье</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Ювелирные шнурки</span>
                                </a>
                            </li>
                        </ul
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Бриллианты</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Помолвочные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Из белого золота</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Колье</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Крестики</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Броши</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Ребенку</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Украшения с камнями</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Бриллиант</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Сапфир</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Изумруд</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Рубин</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Топаз</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Раухтопаз</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Жемчуг</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Аметист</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Цитрин</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Гранат</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Хризолит</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Серебро</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Цепочки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Крестики</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Иконки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Пирсинг</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Этнический орнамент</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Старославянские обереги</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Бусины шарм</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Свадьба</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Обручальные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Помолвочные кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Свадебные подарки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Юбилей свадьби</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level mega-menu-link__premium">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">DIAMONDS - премиум-бренд</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Колье</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#"">Каталог</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list mobile-dropdown_second-level">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Кольца</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серьги</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Подвески</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Сертификаты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Печатки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Часы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Броши</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Зажимы</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Запонки</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Пирсинг</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Коллекции</a>
                    <div class="mega-menu_dropbox">
                        <div class="mega-menu_banner">
                            <img class="mega-menu_banner-img" src="https://www.zolotoyvek.ua/media/banner/image/cache/294x508-frame-255-255-255-zoom/s/e/sergi_3.jpg" alt="">
                        </div>
                        <ul class="mega-menu_list">
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Коллекция "Корона"</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221673.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Белое золото</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221722_1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с топазами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142540007-_-__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Серебро с фианитами</span>
                                </a>
                            </li>
                            <li class="mega-menu_dropbox-item">
                                <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                    <img class="mega-menu-link_thumbnail"
                                         src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14253779-2__1.jpg"
                                         alt="">
                                    <span class="mega-menu-link_thumbnail-title">Украшения с сапфирами</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="mega-menu_item mega-menu_item__top-level">
                    <a class="mega-menu-link mega-menu-link__top-level" href="#">Комплекты</a>
                </li>
            </ul>
        </div>
    </div>
</div>



