<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="mobile-nav" data-mage-init='{"mobileNav":{}}'>
    <div class="container">
        <div class="navbar_item-icon-holder mobile-nav_icon" data-action="show-mobile-dropdown">
            <a href="#" class="navbar_item-burger">
                <span class="icon icon__bg-burger"></span>
            </a>
        </div>
        <div class="navbar_item-icon-holder mobile-nav_icon">
            <a href="#" class="navbar_item-icon-link">
                <span class="icon icon__logo"></span>
            </a>
        </div>
        <div class="navbar_item-icon-holder mobile-nav_icon">
            <a href="#" class="navbar_item-icon-link">
                <span class="icon icon__bg-cart"></span>
            </a>
        </div>
    </div>
</div>
<div class="mobile-nav_dropdown mobile-nav_dropdown__hide">
    <div class="mobile-nav_close" data-action="hide-mobile-dropdown"></div>
    <div class="mega-menu_dropdown-box">
        <div class="mobile-nav_dropdown-header" >Каталог</div>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Кольца</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Серьги</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Подвески</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Цепочки</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Бриллианты</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Украшения с камнями</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Серебро</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">DIAMONDS - премиум-бренд</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link mobile-nav_dropdown-link__bold" data-action="show-mobile-dropdown_second-level">Каталог</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Каталог</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14212922.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Кольца</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14221609-01-1-255.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Серьги</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14231344.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Подвески</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x1427101-01-0-5070.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Браслеты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142icon_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Сертификаты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x14219023.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Печатки</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x142_-302_1.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Часы</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/catalog/product/cache/cat_resized/142x1424099_1.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Броши</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mobile-nav_dropdown-link">
                                <span class="mobile-nav_dropdown-more">Все товары</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Коллекции</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link" data-action="show-mobile-dropdown_second-level">Комплекты</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Коллекции</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file.jpg" alt="">
                                <span class="mega-menu-link_thumbnail-title">Черные бриллианты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link mega-menu-link__insert-level">
                                <img class="mega-menu-link_thumbnail" src="https://www.zolotoyvek.ua/media/adminforms/customlinks/cache/1/cache/142x142/5e06319eda06f020e43594a9c230972d/f/i/file_2.jpg" alt="category img">
                                <span class="mega-menu-link_thumbnail-title">Украшения с изумрудами</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-map-marker-alt"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Доставка и оплата</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Наши магазины</a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link">Акции</a>
            </li>
        </ul>
        <ul class="mobile-nav_dropdown-list">
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-arrows-alt"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Отследить заказ</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-shipping-fast"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Бесплатная доставка</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-retweet"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Обмен 14 дней</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-cart-plus"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Бесплатная бронь в магазине</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-credit-card"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Как оплатить</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <span class="mobile-nav_dropdown-link mobile-nav_dropdown-more" data-action="show-mobile-dropdown_second-level">Больше</span>
                <div class="mobile-nav_dropdown__second-level">
                    <ul class="mobile-nav_dropdown-list">
                        <li class="mobile-nav_dropdown-item">
                            <span class="mega-menu_btn-back" data-action="hide-mobile-dropdown_second-level">Больше</span>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">О нас</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Производство</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Гарантия качества</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Обмен и возврат</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Рассрочка и кредит</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Контакты</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Дисконтная программа</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Ювелирные мастерские</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Новости</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Вакансии</span>
                            </a>
                        </li>
                        <li class="mobile-nav_dropdown-item">
                            <a href="#" class="mega-menu-link">
                                <span class="mobile-nav_dropdown-link__without-icon">Вопрос-Ответ</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-search"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Поиск товаров</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="far fa-calendar-check"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Подбор товаров</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-phone"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">099 80 90 833</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="far fa-user"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Войти</span>
                </a>
            </li>
            <li class="mobile-nav_dropdown-item">
                <a href="#" class="mobile-nav_dropdown-link mobile-nav_dropdown-link__with-icon">
                    <i class="fas fa-hand-holding-heart"></i>
                    <span class="mobile-nav_dropdown-link__with-icon-label">Мой золотой век</span>
                </a>
            </li>
        </ul>
    </div>
</div>