<?php
/**
 * @author Grom Olga <GromOlga.work@gmail.com>
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<div class="header-top-line_item header-dropdown_btn" data-action="header-dropdown_btn" data-mage-init='{"TopLine": {}}'>
    <span>0 800 302 505</span>
    <div class="header-dropdown_content">
        <p>Режим работы:</p>
        <p>
            Пн-Сб 09:00-21:00;</br>
            Вс 09:00-20:00
        </p>
    </div>
</div>
